{"type": "player_stats", "title": "KeonTwitch's Apex Legends Overview", "user_id": "KeonTwitch", "views": "39,032 views", "level": "2,448", "total_kills": "38,373", "total_damage": "2,520,416", "total_matches": "200", "br_rank_label": "Apex Predator", "br_mmr": "21,445", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "injadevin07's Apex Legends Overview", "user_id": "jadevin07", "views": "4,346 views", "level": "2,565", "total_kills": "31,830", "total_damage": "9,134,224", "total_matches": "1,574", "br_rank_label": "Apex Predator", "br_mmr": "11,197", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "JamessFearless's Apex Legends Overview", "user_id": "JamessFearl", "views": "1,805 views", "level": "3,396", "total_kills": "58,041", "total_damage": "14,919,955", "total_matches": "64,609", "br_rank_label": "Apex Predator", "br_mmr": "11,209", "arenas_rank_label": "Bronze 2", "areans_mmr": "1,093", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Verloxxs's Apex Legends Overview", "user_id": "Verlo", "views": "1,772 views", "level": "1,716", "total_kills": "30,007", "total_damage": "3,344,324", "total_matches": "780", "br_rank_label": "Apex Predator", "br_mmr": "11,296", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "Zr mori's Apex Legends Overview", "user_id": "Zr mo", "views": "2,224 views", "level": "2,543", "total_kills": "40,525", "total_damage": "2,129,055", "total_matches": "26", "br_rank_label": "Apex Predator", "br_mmr": "11,399", "arenas_rank_label": "Platinum 1", "areans_mmr": "6,033", "recent_legend": "Lifeline"}
{"type": "player_stats", "title": "Corzafade's Apex Legends Overview", "user_id": "Corzafa", "views": "1,562 views", "level": "2,318", "total_kills": "28,848", "total_damage": "8,459,489", "total_matches": "464", "br_rank_label": "Apex Predator", "br_mmr": "11,644", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Revenant"}
{"type": "player_stats", "title": "vxkz's Apex Legends Overview", "user_id": "kz", "views": "2,377 views", "level": "1,486", "total_kills": "5,901", "total_damage": "2,327,846", "total_matches": "399", "br_rank_label": "Apex Predator", "br_mmr": "11,742", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "Igrindapexagain's Apex Legends Overview", "user_id": "Igrindapexaga", "views": "17,170 views", "level": "1,437", "total_kills": "34,188", "total_damage": "170", "total_matches": "1,992", "br_rank_label": "Apex Predator", "br_mmr": "11,778", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Ash"}
{"type": "player_stats", "title": "ightstarjo's Apex Legends Overview", "user_id": "htstarjo", "views": "348 views", "level": "1,121", "total_kills": "15,462", "total_damage": "1,218,423", "total_matches": "1,895", "br_rank_label": "Apex Predator", "br_mmr": "11,781", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Valkyrie"}
{"type": "player_stats", "title": "Ok aeriu's Apex Legends Overview", "user_id": "k aeriu", "views": "1,639 views", "level": "1,805", "total_kills": "21,395", "total_damage": "3,347,062", "total_matches": "725", "br_rank_label": "Apex Predator", "br_mmr": "10,192", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "yphoon-a-'s Apex Legends Overview", "user_id": "yphoon-a-", "views": "135 views", "level": "745", "total_kills": "14,276", "total_damage": "3,955,667", "total_matches": "8,551", "br_rank_label": "Master", "br_mmr": "10,198", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "oaR_BaronfuI's Apex Legends Overview", "user_id": "oaR_BaronfuI", "views": "8,058 views", "level": "3,519", "total_kills": "73,759", "total_damage": "5,669,542", "total_matches": "31", "br_rank_label": "Apex Predator", "br_mmr": "10,201", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Jax_fps's Apex Legends Overview", "user_id": "Jax_f", "views": "457 views", "level": "1,745", "total_kills": "29,007", "total_damage": "6,532,112", "total_matches": "18,097", "br_rank_label": "Apex Predator", "br_mmr": "10,206", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Lifeline"}
{"type": "player_stats", "title": "heRattpackx's Apex Legends Overview", "user_id": "heRattpack", "views": "1,681 views", "level": "3,535", "total_kills": "67,439", "total_damage": "17,275,689", "total_matches": "2,624", "br_rank_label": "Apex Predator", "br_mmr": "10,209", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "DregoPK's Apex Legends Overview", "user_id": "DregoPK", "views": "1,653 views", "level": "3,696", "total_kills": "48,476", "total_damage": "15,113,541", "total_matches": "4,526", "br_rank_label": "Apex Predator", "br_mmr": "10,222", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "ltsRod's Apex Legends Overview", "user_id": "ltsRo", "views": "334 views", "level": "802", "total_kills": "4,195", "total_damage": "1,759,619", "total_matches": "1,915", "br_rank_label": "Apex Predator", "br_mmr": "10,247", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "owdELife's Apex Legends Overview", "user_id": "owdELif", "views": "577 views", "level": "2,221", "total_kills": "25,029", "total_damage": "156.00", "total_matches": "110", "br_rank_label": "Master", "br_mmr": "10,269", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Horizon"}
{"type": "player_stats", "title": "Fa_KoKoPuffs's Apex Legends Overview", "user_id": "Fa_KoKoPuff", "views": "1,392 views", "level": "2,328", "total_kills": "33,078", "total_damage": "5,513,331", "total_matches": "6,007", "br_rank_label": "Master", "br_mmr": "10,274", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "bmmeech's Apex Legends Overview", "user_id": "bmmeech", "views": "2,054 views", "level": "3,075", "total_kills": "41,224", "total_damage": "11,801,991", "total_matches": "346.00", "br_rank_label": "Apex Predator", "br_mmr": "10,907", "arenas_rank_label": "Bronze 3", "areans_mmr": "481", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "INR2KBC's Apex Legends Overview", "user_id": "INR2KBC", "views": "2,424 views", "level": "483", "total_kills": "3,657", "total_damage": "1,391,013", "total_matches": "1,551", "br_rank_label": "Apex Predator", "br_mmr": "10,284", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "YouRxTrqsh's Apex Legends Overview", "user_id": "YouRxTrqsh", "views": "1,248 views", "level": "1,759", "total_kills": "26,533", "total_damage": "5,100,172", "total_matches": "3,407", "br_rank_label": "Apex Predator", "br_mmr": "10,289", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Horizon"}
{"type": "player_stats", "title": "Bronnism's Apex Legends Overview", "user_id": "Bronnism", "views": "731 views", "level": "1,104", "total_kills": "10,269", "total_damage": "1,132,676", "total_matches": "16", "br_rank_label": "Apex Predator", "br_mmr": "10,293", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "oat's Apex Legends Overview", "user_id": "oat", "views": "3,275 views", "level": "1,363", "total_kills": "4,675", "total_damage": "1,711,568", "total_matches": "6,871", "br_rank_label": "Apex Predator", "br_mmr": "10,300", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bloodhound"}
{"type": "player_stats", "title": "ightRadio's Apex Legends Overview", "user_id": "htRadio", "views": "383 views", "level": "1,188", "total_kills": "11,058", "total_damage": "2,445,811", "total_matches": "8,794", "br_rank_label": "Apex Predator", "br_mmr": "10,381", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "E_trillaGus_1dP's Apex Legends Overview", "user_id": "E_trillaGus_1dP", "views": "707 views", "level": "282", "total_kills": "3,760", "total_damage": "0", "total_matches": "0", "br_rank_label": "Master", "br_mmr": "10,422", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "Ectohloks's Apex Legends Overview", "user_id": "Ectohlok", "views": "5,391 views", "level": "1,547", "total_kills": "20,003", "total_damage": "5,923,752", "total_matches": "3,560", "br_rank_label": "Apex Predator", "br_mmr": "10,330", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "Highhkev's Apex Legends Overview", "user_id": "Highhk", "views": "2,045 views", "level": "1,881", "total_kills": "18,395", "total_damage": "3,760,190", "total_matches": "13,446", "br_rank_label": "Apex Predator", "br_mmr": "10,335", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bloodhound"}
{"type": "player_stats", "title": "Clutch_Cadyy's Apex Legends Overview", "user_id": "Clutch_Cadyy", "views": "424 views", "level": "2,467", "total_kills": "51,149", "total_damage": "14,337,126", "total_matches": "4,386", "br_rank_label": "Master", "br_mmr": "10,281", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "Krogre's Apex Legends Overview", "user_id": "Kro", "views": "2,205 views", "level": "1,914", "total_kills": "28,541", "total_damage": "7,264,686", "total_matches": "30.00", "br_rank_label": "Apex Predator", "br_mmr": "10,372", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Call Spades's Apex Legends Overview", "user_id": "Call Spa", "views": "642 views", "level": "1,279", "total_kills": "15,396", "total_damage": "4,915,996", "total_matches": "1,873", "br_rank_label": "Apex Predator", "br_mmr": "10,386", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "liogius's Apex Legends Overview", "user_id": "liogiu", "views": "534 views", "level": "4,052", "total_kills": "45,279", "total_damage": "22,422,836", "total_matches": "2,088", "br_rank_label": "Apex Predator", "br_mmr": "10,363", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "Kanowitz's Apex Legends Overview", "user_id": "Kanowitz", "views": "229 views", "level": "1,485", "total_kills": "20,966", "total_damage": "5,885,364", "total_matches": "1,185", "br_rank_label": "Apex Predator", "br_mmr": "10,389", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "DoIlarTreeAceu's Apex Legends Overview", "user_id": "DoIlarTreeAceu", "views": "2,058 views", "level": "3,810", "total_kills": "86,236", "total_damage": "18,922,417", "total_matches": "531", "br_rank_label": "Apex Predator", "br_mmr": "10,436", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "hrist oh fur's Apex Legends Overview", "user_id": "hrist oh fu", "views": "1,065 views", "level": "859", "total_kills": "14,610", "total_damage": "3,226,699", "total_matches": "52.00", "br_rank_label": "Apex Predator", "br_mmr": "10,448", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Lifeline"}
{"type": "player_stats", "title": "Jodece's Apex Legends Overview", "user_id": "Jodec", "views": "3,266 views", "level": "3,119", "total_kills": "49,697", "total_damage": "13,431,322", "total_matches": "9,321", "br_rank_label": "Apex Predator", "br_mmr": "10,457", "arenas_rank_label": "Silver 2", "areans_mmr": "2,590", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "ltoosh's Apex Legends Overview", "user_id": "ltoosh", "views": "25,004 views", "level": "2,655", "total_kills": "50,131", "total_damage": "2,799,431", "total_matches": "4,573", "br_rank_label": "Apex Predator", "br_mmr": "10,480", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "Fynhenzzz's Apex Legends Overview", "user_id": "Fynhenzzz", "views": "741 views", "level": "2,334", "total_kills": "40,237", "total_damage": "11,665,560", "total_matches": "36,980", "br_rank_label": "Apex Predator", "br_mmr": "10,488", "arenas_rank_label": "Platinum 3", "areans_mmr": "5,200", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "imi818's Apex Legends Overview", "user_id": "mi818", "views": "3,289 views", "level": "1,692", "total_kills": "10,114", "total_damage": "36", "total_matches": "5.10", "br_rank_label": "Apex Predator", "br_mmr": "10,489", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "ilkevobro's Apex Legends Overview", "user_id": "lkevobro", "views": "851 views", "level": "2,055", "total_kills": "20,948", "total_damage": "2,132,574", "total_matches": "19,548", "br_rank_label": "Apex Predator", "br_mmr": "10,495", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "PayPluto's Apex Legends Overview", "user_id": "PayPluto", "views": "234 views", "level": "2,310", "total_kills": "33,409", "total_damage": "10,609,440", "total_matches": "30,525", "br_rank_label": "Master", "br_mmr": "10,505", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "viswave's Apex Legends Overview", "user_id": "a", "views": "1,830 views", "level": "2,029", "total_kills": "26,039", "total_damage": "6,348,545", "total_matches": "5,818", "br_rank_label": "Master", "br_mmr": "10,516", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "wlsh3r's Apex Legends Overview", "user_id": "lsh3", "views": "1,144 views", "level": "1,698", "total_kills": "9,973", "total_damage": "1,707,526", "total_matches": "8,484", "br_rank_label": "Apex Predator", "br_mmr": "10,550", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "RCO_Nand2o3's Apex Legends Overview", "user_id": "RCO_Nand2o3", "views": "403 views", "level": "1,791", "total_kills": "61,078", "total_damage": "14,057,152", "total_matches": "14,085", "br_rank_label": "Master", "br_mmr": "10,566", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Wockin yt's Apex Legends Overview", "user_id": "Wockin yt", "views": "2,127 views", "level": "1,889", "total_kills": "18,784", "total_damage": "3,381,961", "total_matches": "267", "br_rank_label": "Apex Predator", "br_mmr": "10,582", "arenas_rank_label": "Master", "areans_mmr": "8,423", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "G_xenial's Apex Legends Overview", "user_id": "G_xenial", "views": "2,704 views", "level": "2,617", "total_kills": "64,715", "total_damage": "2,820,689", "total_matches": "34,507", "br_rank_label": "Apex Predator", "br_mmr": "10,583", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Cinicoo's Apex Legends Overview", "user_id": "Cinicoo", "views": "829 views", "level": "2,116", "total_kills": "30,292", "total_damage": "6,576,818", "total_matches": "1,045", "br_rank_label": "Apex Predator", "br_mmr": "10,603", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "Jellie_EQ's Apex Legends Overview", "user_id": "Jellie_EQ", "views": "4,170 views", "level": "2,753", "total_kills": "46,465", "total_damage": "12,332,500", "total_matches": "27,413", "br_rank_label": "Apex Predator", "br_mmr": "10,603", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "oh warlordz's Apex Legends Overview", "user_id": "oh warlordz", "views": "1,308 views", "level": "2,576", "total_kills": "28,464", "total_damage": "8,764,544", "total_matches": "29,468", "br_rank_label": "Apex Predator", "br_mmr": "10,605", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "IakHuI's Apex Legends Overview", "user_id": "IakHuI", "views": "2,829 views", "level": "2,936", "total_kills": "56,882", "total_damage": "16,132,202", "total_matches": "6,604", "br_rank_label": "Master", "br_mmr": "10,622", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "yinJah's Apex Legends Overview", "user_id": "yinJah", "views": "1,812 views", "level": "2,941", "total_kills": "37,467", "total_damage": "8,387,644", "total_matches": "8,089", "br_rank_label": "Apex Predator", "br_mmr": "10,650", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "oschlepp's Apex Legends Overview", "user_id": "oschl", "views": "2,726 views", "level": "2,168", "total_kills": "41,068", "total_damage": "10,525,653", "total_matches": "13,347", "br_rank_label": "Apex Predator", "br_mmr": "10,673", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "Just__jaxx's Apex Legends Overview", "user_id": "Just__ja", "views": "3,373 views", "level": "3,134", "total_kills": "41,530", "total_damage": "10,888,178", "total_matches": "2,059", "br_rank_label": "Apex Predator", "br_mmr": "10,680", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Brooksstyle's Apex Legends Overview", "user_id": "Brooksstyl", "views": "27,396 views", "level": "4,529", "total_kills": "47,834", "total_damage": "10,478,393", "total_matches": "1,553", "br_rank_label": "Apex Predator", "br_mmr": "10,723", "arenas_rank_label": "Gold 2", "areans_mmr": "4,373", "recent_legend": "Wattson"}
{"type": "player_stats", "title": "yxxio's Apex Legends Overview", "user_id": "yxxio", "views": "535 views", "level": "2,137", "total_kills": "69,917", "total_damage": "16,075,670", "total_matches": "864", "br_rank_label": "Apex Predator", "br_mmr": "10,732", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Lifeline"}
{"type": "player_stats", "title": "iniii's Apex Legends Overview", "user_id": "", "views": "1,056 views", "level": "2,536", "total_kills": "29,179", "total_damage": "4,734,485", "total_matches": "1,410", "br_rank_label": "Apex Predator", "br_mmr": "10,615", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "YP apex's Apex Legends Overview", "user_id": "YP a", "views": "1,313 views", "level": "1,911", "total_kills": "24,025", "total_damage": "4,366,159", "total_matches": "3,053", "br_rank_label": "Apex Predator", "br_mmr": "10,753", "arenas_rank_label": "Platinum 2", "areans_mmr": "5,600", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "oggieWaffl3s_FB's Apex Legends Overview", "user_id": "oggieWaffl3s_FB", "views": "3,126 views", "level": "6,022", "total_kills": "70,883", "total_damage": "19,590,510", "total_matches": "415", "br_rank_label": "Apex Predator", "br_mmr": "10,758", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Lifeline"}
{"type": "player_stats", "title": "v_allukaFPS's Apex Legends Overview", "user_id": "_allukaFPS", "views": "1,308 views", "level": "1,967", "total_kills": "30,738", "total_damage": "6,991,105", "total_matches": "3,451", "br_rank_label": "Apex Predator", "br_mmr": "10,767", "arenas_rank_label": "Platinum 3", "areans_mmr": "5,243", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "yrical's Apex Legends Overview", "user_id": "yrical", "views": "766 views", "level": "370", "total_kills": "3,718", "total_damage": "156,099", "total_matches": "784", "br_rank_label": "Apex Predator", "br_mmr": "10,790", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "Walex0tv's Apex Legends Overview", "user_id": "Walex0t", "views": "420 views", "level": "1,322", "total_kills": "29,735", "total_damage": "2,257,028", "total_matches": "149", "br_rank_label": "Apex Predator", "br_mmr": "10,796", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Valkyrie"}
{"type": "player_stats", "title": "onOfThanatosTV's Apex Legends Overview", "user_id": "onOfThanatosTV", "views": "1,636 views", "level": "2,194", "total_kills": "29,019", "total_damage": "5,903,149", "total_matches": "746", "br_rank_label": "Master", "br_mmr": "10,805", "arenas_rank_label": "Platinum 3", "areans_mmr": "5,200", "recent_legend": "Rampart"}
{"type": "player_stats", "title": "y's Apex Legends Overview", "user_id": "y", "views": "3,073 views", "level": "3,602", "total_kills": "74,768", "total_damage": "19,437,414", "total_matches": "13,829", "br_rank_label": "Apex Predator", "br_mmr": "10,811", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "itsyurzaw's Apex Legends Overview", "user_id": "tsyurza", "views": "2,893 views", "level": "3,360", "total_kills": "53,878", "total_damage": "15,209,681", "total_matches": "11,982", "br_rank_label": "Apex Predator", "br_mmr": "10,828", "arenas_rank_label": "Bronze 3", "areans_mmr": "646", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "mokedByJJ's Apex Legends Overview", "user_id": "mokedByJJ", "views": "2,797 views", "level": "2,622", "total_kills": "54,930", "total_damage": "13,046,028", "total_matches": "11,711", "br_rank_label": "Apex Predator", "br_mmr": "10,853", "arenas_rank_label": "Diamond 1", "areans_mmr": "7,891", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "McSkrty's Apex Legends Overview", "user_id": "McSkrty", "views": "4,300 views", "level": "1,848", "total_kills": "35,144", "total_damage": "6,837,673", "total_matches": "567", "br_rank_label": "Master", "br_mmr": "10,856", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "ynew's Apex Legends Overview", "user_id": "y", "views": "3,715 views", "level": "1,901", "total_kills": "21,612", "total_damage": "3,628,776", "total_matches": "310", "br_rank_label": "Apex Predator", "br_mmr": "10,856", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Ash"}
{"type": "player_stats", "title": "ibignicki's Apex Legends Overview", "user_id": "bignick", "views": "1,355 views", "level": "2,258", "total_kills": "27,291", "total_damage": "5,102,485", "total_matches": "18,388", "br_rank_label": "Apex Predator", "br_mmr": "10,874", "arenas_rank_label": "Bronze 3", "areans_mmr": "481", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "NRG_aceu's Apex Legends Overview", "user_id": "NRG_aceu", "views": "22,441 views", "level": "1,134", "total_kills": "67,447", "total_damage": "12,212,891", "total_matches": "3,450", "br_rank_label": "Apex Predator", "br_mmr": "10,882", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Calypt0's Apex Legends Overview", "user_id": "Calypt0", "views": "1,703 views", "level": "2,973", "total_kills": "39,157", "total_damage": "11,478,987", "total_matches": "850.00", "br_rank_label": "Apex Predator", "br_mmr": "10,921", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "outthelando's Apex Legends Overview", "user_id": "outthelando", "views": "1,949 views", "level": "3,834", "total_kills": "105,699", "total_damage": "23,132,089", "total_matches": "21,212", "br_rank_label": "Apex Predator", "br_mmr": "10,814", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "Crewsn_Twitch's Apex Legends Overview", "user_id": "Crewsn_Twitch", "views": "1,397 views", "level": "2,616", "total_kills": "42,886", "total_damage": "2,304,907", "total_matches": "7,875", "br_rank_label": "Apex Predator", "br_mmr": "10,924", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "ImYourWattson's Apex Legends Overview", "user_id": "ImYourWattso", "views": "2,010 views", "level": "3,005", "total_kills": "42,708", "total_damage": "10,634,244", "total_matches": "4,151", "br_rank_label": "Apex Predator", "br_mmr": "10,877", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wattson"}
{"type": "player_stats", "title": "Bigbodyrenzo's Apex Legends Overview", "user_id": "Bigbodyrenzo", "views": "263 views", "level": "636", "total_kills": "27", "total_damage": "381", "total_matches": "4,892", "br_rank_label": "Apex Predator", "br_mmr": "10,938", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bloodhound"}
{"type": "player_stats", "title": "Puh-_-Theed's Apex Legends Overview", "user_id": "Puh-_-Th", "views": "1,521 views", "level": "2,024", "total_kills": "29,113", "total_damage": "6,463,417", "total_matches": "666.00", "br_rank_label": "Apex Predator", "br_mmr": "10,998", "arenas_rank_label": "Bronze 1", "areans_mmr": "1,291", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "januaryytv's Apex Legends Overview", "user_id": "januaryyt", "views": "1,124 views", "level": "1,140", "total_kills": "13,099", "total_damage": "2,504,038", "total_matches": "1,186", "br_rank_label": "Apex Predator", "br_mmr": "11,017", "arenas_rank_label": "Silver 4", "areans_mmr": "1,916", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "BTW_TTV's Apex Legends Overview", "user_id": "BTW_TTV", "views": "1,160 views", "level": "2,469", "total_kills": "63,359", "total_damage": "9,368,692", "total_matches": "38,432", "br_rank_label": "Apex Predator", "br_mmr": "11,086", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "unttin's Apex Legends Overview", "user_id": "untt", "views": "720 views", "level": "2,036", "total_kills": "17,559", "total_damage": "6,186,404", "total_matches": "163", "br_rank_label": "Apex Predator", "br_mmr": "11,138", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "oisenpai's Apex Legends Overview", "user_id": "oisenpa", "views": "909 views", "level": "1,846", "total_kills": "36,563", "total_damage": "9,910,692", "total_matches": "1,777", "br_rank_label": "Apex Predator", "br_mmr": "11,798", "arenas_rank_label": "Platinum 2", "areans_mmr": "5,600", "recent_legend": "Lifeline"}
{"type": "player_stats", "title": "wesomee_Tryhard's Apex Legends Overview", "user_id": "omee_Tryha", "views": "22,858 views", "level": "1,562", "total_kills": "53", "total_damage": "39", "total_matches": "14", "br_rank_label": "Apex Predator", "br_mmr": "11,889", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Fuse"}
{"type": "player_stats", "title": "EwwDaRolla's Apex Legends Overview", "user_id": "EwwDaRolla", "views": "1,717 views", "level": "1,233", "total_kills": "15,174", "total_damage": "132", "total_matches": "12,855", "br_rank_label": "Apex Predator", "br_mmr": "12,151", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Loba"}
{"type": "player_stats", "title": "witch_dooplex's Apex Legends Overview", "user_id": "tch_doopl", "views": "2,297 views", "level": "1,666", "total_kills": "17,889", "total_damage": "4,395,221", "total_matches": "81.00", "br_rank_label": "Apex Predator", "br_mmr": "12,177", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "C9PVPX's Apex Legends Overview", "user_id": "C9PVPX", "views": "4,397 views", "level": "2,585", "total_kills": "39,449", "total_damage": "5,392,314", "total_matches": "330", "br_rank_label": "Apex Predator", "br_mmr": "12,189", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "DylanDubsTv's Apex Legends Overview", "user_id": "DylanDubsT", "views": "715 views", "level": "847", "total_kills": "6,838", "total_damage": "527,415", "total_matches": "2,962", "br_rank_label": "Apex Predator", "br_mmr": "12,232", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "CLG_Vatroh's Apex Legends Overview", "user_id": "CLG_Vatroh", "views": "2,680 views", "level": "2,606", "total_kills": "43,276", "total_damage": "8,793,086", "total_matches": "7,727", "br_rank_label": "Master", "br_mmr": "12,313", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "_FunFPS's Apex Legends Overview", "user_id": "_FunFPS", "views": "10,687 views", "level": "3,357", "total_kills": "62,471", "total_damage": "6,445,570", "total_matches": "46.00", "br_rank_label": "Master", "br_mmr": "12,549", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "'s Apex Legends Overview", "user_id": "", "views": "2,067 views", "level": "1,578", "total_kills": "8,630", "total_damage": "430,436", "total_matches": "0", "br_rank_label": "Apex Predator", "br_mmr": "12,657", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bloodhound"}
{"type": "player_stats", "title": "Kiraa_ttv's Apex Legends Overview", "user_id": "Kiraa_tt", "views": "1,806 views", "level": "1,914", "total_kills": "41,447", "total_damage": "8,599,100", "total_matches": "924", "br_rank_label": "Apex Predator", "br_mmr": "12,864", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Octane"}
{"type": "player_stats", "title": "CLG_Nano's Apex Legends Overview", "user_id": "CLG_Nano", "views": "860 views", "level": "1,935", "total_kills": "23,074", "total_damage": "7,235,666", "total_matches": "1,174", "br_rank_label": "Apex Predator", "br_mmr": "12,993", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "JayeCue's Apex Legends Overview", "user_id": "JayeCu", "views": "44,416 views", "level": "4,417", "total_kills": "132,966", "total_damage": "17,586,191", "total_matches": "1,343.00", "br_rank_label": "Apex Predator", "br_mmr": "13,335", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Bangalore"}
{"type": "player_stats", "title": "M_Noko's Apex Legends Overview", "user_id": "M_Noko", "views": "7,901 views", "level": "2,994", "total_kills": "73,059", "total_damage": "14,768,696", "total_matches": "5,418", "br_rank_label": "Apex Predator", "br_mmr": "13,370", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "hekineTV's Apex Legends Overview", "user_id": "hekineTV", "views": "3,723 views", "level": "4,497", "total_kills": "99,479", "total_damage": "9,854,469", "total_matches": "276", "br_rank_label": "Apex Predator", "br_mmr": "13,593", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "OriolesRule0613's Apex Legends Overview", "user_id": "olesRule0613", "views": "21,675 views", "level": "2,921", "total_kills": "44,292", "total_damage": "10,832,022", "total_matches": "241", "br_rank_label": "Apex Predator", "br_mmr": "14,291", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Kotigami's Apex Legends Overview", "user_id": "Kotigam", "views": "1,980 views", "level": "4,033", "total_kills": "74,345", "total_damage": "18,826,090", "total_matches": "1", "br_rank_label": "Apex Predator", "br_mmr": "14,203", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "bleaaonyoutube's Apex Legends Overview", "user_id": "bleaaonyoutub", "views": "2,141 views", "level": "1,502", "total_kills": "17,059", "total_damage": "2,442,069", "total_matches": "656", "br_rank_label": "Apex Predator", "br_mmr": "14,566", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Gibraltar"}
{"type": "player_stats", "title": "NRG_Sweetd's Apex Legends Overview", "user_id": "NRG_Sweet", "views": "82,392 views", "level": "2,844", "total_kills": "30,779", "total_damage": "831,923", "total_matches": "41", "br_rank_label": "Apex Predator", "br_mmr": "15,482", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "Piouds's Apex Legends Overview", "user_id": "Piou", "views": "11,161 views", "level": "2,024", "total_kills": "27,722", "total_damage": "1,868,518", "total_matches": "776", "br_rank_label": "Apex Predator", "br_mmr": "17,700", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "BI_Gsnkryu's Apex Legends Overview", "user_id": "BI_Gsnkryu", "views": "73,983 views", "level": "2,874", "total_kills": "33,017", "total_damage": "24,215", "total_matches": "0", "br_rank_label": "Apex Predator", "br_mmr": "17,753", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
{"type": "player_stats", "title": "ProbGarrett-FB's Apex Legends Overview", "user_id": "ProbGarrett-FB", "views": "2,188 views", "level": "3,043", "total_kills": "67,381", "total_damage": "12,376,978", "total_matches": "4,887", "br_rank_label": "Apex Predator", "br_mmr": "18,142", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Wraith"}
{"type": "player_stats", "title": "vmessiahttv's Apex Legends Overview", "user_id": "messiahtt", "views": "5,239 views", "level": "1,963", "total_kills": "11,235", "total_damage": "122,383", "total_matches": "183.00", "br_rank_label": "Apex Predator", "br_mmr": "19,579", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Horizon"}
{"type": "player_stats", "title": "G2_Dezignful's Apex Legends Overview", "user_id": "G2_Dezignful", "views": "13,695 views", "level": "2,379", "total_kills": "33,615", "total_damage": "4,353,389", "total_matches": "1,436", "br_rank_label": "Apex Predator", "br_mmr": "19,787", "arenas_rank_label": "Bronze 4", "areans_mmr": "0", "recent_legend": "Pathfinder"}
